apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-secret
    solvers:
    - http01:
       ingress:
         name: web-ingress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging-certificate
  namespace: app
spec:
  secretName: letsencrypt-staging-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
  commonName: faheem.saqlainmushtaq.com
  dnsNames:
  - faheem.saqlainmushtaq.com
