apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-secret
    solvers:
    - http01:
       ingress:
         name: web-ingress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production-certificate
  namespace: app
spec:
  secretName: letsencrypt-production-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-production
  commonName: app.cloudgeeks.tk
  dnsNames:
  - app.cloudgeeks.tk


# kubectl get certs -n app
# kubectl get issuer -n app
# kubectl get secrets -n app
# kubectl get secrets -n ap
# kubectl get secrets/letsencrypt-production-secret -o yaml -n app
